Cappua/cappua-be

app/models/track.rb
app/models/user.rb
app/models/verse.rb
app/models/vote.rb
config/application.rb
db/migrate/20210218000325_create_users.rb
db/migrate/20210218001056_create_tracks.rb
db/migrate/20210218001150_create_verses.rb
db/migrate/20210218001223_create_votes.rb
db/schema.rb
spec/models/track_spec.rb
spec/models/user_spec.rb
spec/models/verse_spec.rb
spec/models/vote_spec.rb

Migrate user, track, verse, vote tables, create and test models for each of them as well

Migrations and models

---

app/controllers/api/v1/upload_controller.rb
app/models/competition.rb
app/models/track.rb
app/models/verse.rb
app/serializers/competition_serializer.rb
app/serializers/verse_serializer.rb
db/migrate/20210222182047_add_title_to_verses.rb
db/migrate/20210222183145_change_tracks_to_competitions.rb
db/migrate/20210222184218_remove_tracks_from_verses.rb
db/migrate/20210222184703_add_competitions_to_verses.rb
db/migrate/20210222184937_add_description_to_competitions.rb
db/schema.rb
db/seeds.rb
spec/factories.rb
spec/models/competition_spec.rb
spec/models/verse_spec.rb
spec/requests/api/v1/upload_request_spec.rb

Add column title to verses, change tracks table to competitions, add genre, description, and rules column 
This PR closes #31 #36

Database changes

---

app/graphql/types/competition_type.rb
app/graphql/types/query_type.rb
spec/factories.rb
spec/requests/queries/competition_query_spec.rb

Create CompetitionType, add to query type, create test
This PR closes #32

Single competition query

---

app/graphql/types/query_type.rb
app/graphql/types/verse_type.rb
spec/factories.rb
spec/requests/queries/verse_query_spec.rb

- Create test for single verse query
- Create query to get a single verse
- Create test for getting all verses through graphql
- Create query to get all verses through GraphQL
This Pr creates queries to get all verses and a single verse by id
This PR closes #26 and closes #30

Create verse and verses queries

---

Gemfile
Gemfile.lock
app/graphql/mutations/create_vote.rb
app/graphql/mutations/delete_vote.rb
app/graphql/types/mutation_type.rb
app/graphql/types/user_type.rb
app/graphql/types/verse_type.rb
app/graphql/types/vote_type.rb
app/models/vote.rb
config/initializers/cors.rb
spec/factories.rb
spec/requests/mutations/vote_mutation_spec.rb

Vote mutations

---

app/graphql/types/verse_type.rb

Co-authored-by: Sage Gonzales <65799246+SageOfCode@users.noreply.github.com>
Co-authored-by: Brian Liu <67594471+the-color-bliu@users.noreply.github.com>
Co-authored-by: Cooper Terrones <67164959+coopterrones@users.noreply.github.com>
Co-authored-by: Damaceo Vincent Howard <62954974+demaceo@users.noreply.github.com>
Co-authored-by: Nick King <68172332+nmking22@users.noreply.github.com>
Bug fix to VoteType in VerseType vote field

Change Types::Vote to Types::VoteType

---

app/graphql/types/competition_type.rb
app/graphql/types/user_type.rb
app/graphql/types/verse_type.rb
spec/factories.rb
spec/requests/api/v1/upload_request_spec.rb
spec/requests/queries/competition_query_spec.rb
spec/requests/queries/verse_query_spec.rb

Adds functionality for verses by competition query
* Adds upvoted and voteCount fields to verses
* Connects competitions, verses and users through type fields
* Tests all added functionality
Resolves #33 

Verses by competition query

---

app/controllers/api/v1/upload_controller.rb

Updates upload folder name for competitions

Change S3 bucket name for competitions

---

.travis.yml

First attempt to create deployments to AWS through Travis-CI
Will use s3 bucket specified to store code; elastic beanstalk pulls code from there.

Add elasticbeanstalk configuration to .travis.yml

---

app/graphql/types/last_winner.rb
app/graphql/types/query_type.rb
app/graphql/types/user_type.rb
app/models/verse.rb
config/routes.rb
spec/models/verse_spec.rb
spec/requests/queries/last_winner_query_spec.rb

Create Query for lastWinner and appropriate test, additional minor updates and fixes
This PR closes #28

Last winner query

---

.gitignore
spec/rails_helper.rb

Co-authored-by: Brian Liu <67594471+the-color-bliu@users.noreply.github.com>
Co-authored-by: Eugene Theriault <45305677+ETBassist@users.noreply.github.com>
Co-authored-by: Nick King <68172332+nmking22@users.noreply.github.com>
This PR closes #52

Add simplecov for coverage report

---

db/seeds.rb

Co-authored-by: Cooper Terrones <67164959+coopterrones@users.noreply.github.com>
Co-authored-by: Damaceo Vincent Howard <62954974+demaceo@users.noreply.github.com>

Make all profiles Tom

---

app/graphql/types/query_type.rb
app/graphql/types/top_three_contenders.rb
app/models/verse.rb
spec/models/verse_spec.rb
spec/requests/queries/top_three_contenders_spec.rb

Create type, add method to query type, add method to verse model, create respective tests
This PR closes #29

Top three query

---

app/graphql/mutations/update_comp_image.rb
app/graphql/types/competition_type.rb
app/graphql/types/mutation_type.rb
db/migrate/20210225165316_add_image_to_competition.rb
db/schema.rb
spec/requests/mutations/update_comp_image_spec.rb
spec/requests/queries/competition_query_spec.rb

Comp image

---

app/graphql/types/query_type.rb
app/graphql/types/user_type.rb
spec/requests/queries/user_query_spec.rb

- Create test for query to get a single user by id
- Create query for getting a user by id
This PR creates a query to get a single user by ID
This PR closes #65

Create User Query

---

app/controllers/api/v1/upload_controller.rb
app/facades/competition_facade.rb
app/facades/verse_facade.rb
app/services/upload_service.rb
spec/facades/competition_facade_spec.rb
spec/facades/verse_facade_spec.rb
spec/requests/api/v1/upload_request_spec.rb
spec/services/upload_service_spec.rb

* Refactors upload create action into controller/facade/service architecture
* Adds unit tests for new facades
* Adds unit tests for new service
Resolves #22 

Upload Controller Refactor

---

app/graphql/mutations/login_user.rb
app/graphql/types/mutation_type.rb
app/graphql/types/user_type.rb
db/migrate/20210227230329_add_usersub_to_user.rb
db/migrate/20210227235430_remove_image_from_user.rb
db/schema.rb
db/seeds.rb
spec/factories.rb
spec/requests/mutations/user_login_spec.rb

User login

---

app/models/user.rb
app/models/verse.rb

Co-authored-by: Brian Liu <67594471+the-color-bliu@users.noreply.github.com>
Co-authored-by: Cooper Terrones <67164959+coopterrones@users.noreply.github.com>
Co-authored-by: Damaceo Vincent Howard <62954974+demaceo@users.noreply.github.com>
Co-authored-by: Eugene Theriault <45305677+ETBassist@users.noreply.github.com>
Co-authored-by: Nick King <68172332+nmking22@users.noreply.github.com>

Add unique email validation

---

.travis.yml

Revise .travis.yml to attempt automatic deployment

---

app/graphql/types/query_type.rb
spec/requests/queries/competition_query_spec.rb

* Change competition query argument from competition ID to month
* Adapt tests to match change

Competition by month

---

db/seeds.rb

* Adds relevant audio paths for january verse/competition seeds

Add january audio file seeds

---

db/seeds.rb

More seeds, update images and minor changes to competition info

---

app/controllers/api/v1/upload_controller.rb
app/models/competition.rb
spec/models/competition_spec.rb
spec/requests/api/v1/upload_request_spec.rb

* Adds tests and functionality for additional POST /upload sad paths with descriptive error messages
This PR closes #85

Upload Endpoint Sad Paths

---

app/facades/competition_facade.rb
app/facades/verse_facade.rb

* Fixes bug where uploads were going into the wrong folder in the s3 bucket

Remove leading slash from upload key

---

db/seeds.rb

Optional PR that adds a random surname to our user names. 

Add an array to give our user names more flare
